### ISSUE TITLE
Checklist for going live

### ISSUE THREAD

**Issue by andrie** [rstudio/team-admin.rstudio.com#5]
Unrelated to content:

- [x] Use CC-BY-NC license (#8)
- [x] Use RStudio logo in header (#13)
- [x] Enable automatic building on Netlify
- [x] Add RStudio contact information (etc.) in footer
- [x] Create redirect links from old site that maps onto new site
- [x] Add Google Analytics code
- [x] Change this repo from "private" to "public"

Going live:

- [x] Switch domain name on Netlify
- [x] Change URL that `make test-prod-links` uses (#32)

Related to content:

- [x] Review RSP section
- [x] Review Connect section (#10)
- [x] Review RSPM section
- [x] Review Troubleshooting section
